modelName:
  # =======================================================
  # 국내 예보모델
  # =======================================================
  #********************************************************
  # KIM-3K
  #********************************************************
  KIM-3K_PRES:
    varName:
      - name: 'UGRD_P0_L100_GLC0'
        level: [ '23','22','21','20','19','18','17' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
      - name: 'VGRD_P0_L100_GLC0'
        level: [ '23','22','21','20','19','18','17' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
    tblName: 'TB_INT_MODEL'
  KIM-3K_UNIS:
    varName:
      - name: 'DSWRFLX_P0_L1_GLC0'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'DIFSWRF_P0_L1_GLC0'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
    tblName: 'TB_INT_MODEL'
  #********************************************************
  # LDAPS-1.5K
  #********************************************************
  LDAPS-1.5K_PRES:
    varName:
      - name: 'UGRD_P0_L100_GLC0'
        level: [ '23','22','21','20','19','18','17' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
      - name: 'VGRD_P0_L100_GLC0'
        level: [ '23','22','21','20','19','18','17' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
  LDAPS-1.5K_UNIS:
    varName:
      - name: 'UGRD_P0_L103_GLC0'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'VGRD_P0_L103_GLC0'
        level: [ '-1' ]
        colName: [ 'V' ]
      - name: 'DSWRF_P8_L1_GLC0_avg1h'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'CSUSF_P8_L103_GLC0_avg1h'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'VBDSF_P8_L1_GLC0_avg1h'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'CFNSF_P8_L103_GLC0_avg1h'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
  #********************************************************
  # RDAPS-12K
  #********************************************************
  RDAPS-12K_PRES:
    varName:
      - name: 'UGRD_P0_L100_GLC0'
        level: [ '23','22','21','20','19','18','17' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
      - name: 'VGRD_P0_L100_GLC0'
        level: [ '23','22','21','20','19','18','17' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
  RDAPS-12K_UNIS:
    varName:
      - name: 'UGRD_P0_L103_GLC0'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'VGRD_P0_L103_GLC0'
        level: [ '-1' ]
        colName: [ 'V' ]
      - name: 'DSWRF_P8_L1_GLC0_avg3h'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'USWRF_P8_L8_GLC0_avg3h'
        level: [ '-1' ]
        colName: [ 'SW_U' ]
      - name: 'CSDSF_P8_L1_GLC0_avg3h'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'CSUSF_P8_L103_GLC0_avg3h'
        level: [ '-1' ]
        colName: [ 'SW_UC' ]
  #********************************************************
  # KIER-LDAPS-2K
  #********************************************************
  KIER-LDAPS-2K_PRES:
    varName:
      - name: 'ua'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
        unit: 'm/s'
      - name: 'va'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
        unit: 'm/s'
      - name: 'z'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'G1000','G975','G950','G925','G900','G875','G850' ]
        unit: 'dm'
      - name: 'ALBEDO'
        level: [ '-1' ]
        colName: [ 'ALB' ]
      - name: 'T2'
        level: [ '-1' ]
        colName: [ 'TM' ]
      - name: 'PSFC'
        level: [ '-1' ]
        colName: [ 'PRE' ]
      - name: 'RH'
        level: [ '-1' ]
        colName: [ 'RH' ]
    tblName: 'TB_INT_MODEL'
  KIER-LDAPS-2K_UNIS:
    varName:
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  KIER-LDAPS-2K-30M_UNIS:
    varName:
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  KIER-LDAPS-2K-60M_UNIS:
    varName:
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  #********************************************************
  # KIER-RDAPS-3K
  #********************************************************
  KIER-RDAPS-3K_PRES:
    varName:
      - name: 'ua'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
        unit: 'm/s'
      - name: 'va'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
        unit: 'm/s'
      - name: 'z'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'G1000','G975','G950','G925','G900','G875','G850' ]
        unit: 'dm'
      - name: 'ALBEDO'
        level: [ '-1' ]
        colName: [ 'ALB' ]
      - name: 'T2'
        level: [ '-1' ]
        colName: [ 'TM' ]
      - name: 'PSFC'
        level: [ '-1' ]
        colName: [ 'PRE' ]
      - name: 'RH'
        level: [ '-1' ]
        colName: [ 'RH' ]
    tblName: 'TB_INT_MODEL'
  KIER-RDAPS-3K_UNIS:
    varName:
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  KIER-RDAPS-3K-30M_UNIS:
    varName:
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  KIER-RDAPS-3K-60M_UNIS:
    varName:
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  #********************************************************
  # KIER-WIND
  #********************************************************
  KIER-WIND_ALL:
    varName:
      - name: 'ua'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
        unit: 'm/s'
      - name: 'va'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
        unit: 'm/s'
      - name: 'z'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'G1000','G975','G950','G925','G900','G875','G850' ]
        unit: 'dm'
      - name: 'ALBEDO'
        level: [ '-1' ]
        colName: [ 'ALB' ]
      - name: 'T2'
        level: [ '-1' ]
        colName: [ 'TM' ]
      - name: 'PSFC'
        level: [ '-1' ]
        colName: [ 'PRE' ]
      - name: 'RH'
        level: [ '-1' ]
        colName: [ 'RH' ]
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  KIER-WIND-30M_ALL:
    varName:
      - name: 'ua'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
        unit: 'm/s'
      - name: 'va'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
        unit: 'm/s'
      - name: 'z'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'G1000','G975','G950','G925','G900','G875','G850' ]
        unit: 'dm'
      - name: 'ALBEDO'
        level: [ '-1' ]
        colName: [ 'ALB' ]
      - name: 'T2'
        level: [ '-1' ]
        colName: [ 'TM' ]
      - name: 'PSFC'
        level: [ '-1' ]
        colName: [ 'PRE' ]
      - name: 'RH'
        level: [ '-1' ]
        colName: [ 'RH' ]
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  KIER-WIND-60M_ALL:
    varName:
      - name: 'ua'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'U1000','U975','U950','U925','U900','U875','U850' ]
        unit: 'm/s'
      - name: 'va'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'V1000','V975','V950','V925','V900','V875','V850' ]
        unit: 'm/s'
      - name: 'z'
        level: [ '1000', '975', '950', '925' ,'900', '875', '850' ]
        colName: [ 'G1000','G975','G950','G925','G900','G875','G850' ]
        unit: 'dm'
      - name: 'ALBEDO'
        level: [ '-1' ]
        colName: [ 'ALB' ]
      - name: 'T2'
        level: [ '-1' ]
        colName: [ 'TM' ]
      - name: 'PSFC'
        level: [ '-1' ]
        colName: [ 'PRE' ]
      - name: 'RH'
        level: [ '-1' ]
        colName: [ 'RH' ]
      - name: 'SWDOWN'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'SWDOWNC'
        level: [ '-1' ]
        colName: [ 'SW_DC' ]
      - name: 'GSW'
        level: [ '-1' ]
        colName: [ 'SW_NET' ]
      - name: 'SWDDNI'
        level: [ '-1' ]
        colName: [ 'SW_DDNI' ]
      - name: 'SWDDIF'
        level: [ '-1' ]
        colName: [ 'SW_DDIF' ]
      - name: 'U10'
        level: [ '-1' ]
        colName: [ 'U' ]
      - name: 'V10'
        level: [ '-1' ]
        colName: [ 'V' ]
    tblName: 'TB_INT_MODEL'
  # =======================================================
  # 국외 예보모델
  # =======================================================
  #********************************************************
  # ECMWF
  #********************************************************
  ECMWF:
    varName:
      - name: 'SSRD_GDS0_SFC'
        level: [ '1','2','3','4','5','6' ]
        colName: [ 'SW_DDNI' ]
      - name: 'FDIR_GDS0_SFC'
        level: [ '1','2','3','4','5','6' ]
        colName: [ 'SW_DDIF' ]
      - name: 'CDIR_GDS0_SFC'
        level: [ '1','2','3','4','5','6' ]
        colName: [ 'SW_DDIF' ]
    tblName: 'TB_INT_MODEL'
  #********************************************************
  # GFS
  #********************************************************
  GFS-25K_ALL:
    varName:
      - name: 'UGRD_P0_L100_GLL0'
        level: [ '40', '39', '38', '37', '36', '35' ]
        colName: [ 'U1000', 'U975', 'U950', 'U925', 'U900', 'U850' ]
      - name: 'VGRD_P0_L100_GLL0'
        level: [ '40', '39', '38', '37', '36', '35' ]
        colName: [ 'V1000', 'V975', 'V950', 'V925', 'V900', 'V850' ]
      - name: 'DSWRF_P8_L1_GLL0_avg'
        level: [ '-1' ]
        colName: [ 'SW_D' ]
      - name: 'USWRF_P8_L8_GLL0_avg'
        level: [ '-1' ]
        colName: [ 'SW_UC' ]
    tblName: 'TB_INT_MODEL'